server:
  port: 447
  ssl:
    key-store: C:\Users\11722\keystore
    key-store-password: abcdefg
    #key-store-type: PKCS12
    key-alias: tomcat #证书别名，建议设置为证书域名，否则可能报错（Invalid keystore format），如：www.baidu.cn
spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: consumer80
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    mz.springcloud.feign.FeignService: debug