server:
  port: 7002

eureka:
  instance:
    hostname: eurekaServer #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    enable-self-preservation: false #关闭自我保护(默认是开启自我保护)
    eviction-interval-timer-in-ms: 2000 #Eureka Server 清理无效节点的频率，默认 60000 毫秒（60 秒）